# Always validate the PR title AND all the commits
titleAndCommits: false
# Always validate all commits, and ignore the PR title
commitsOnly: false
# Always validate the PR title, and ignore the commits
titleOnly: true
